// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXpVJcICvbNnVdjPxPNCD8FIY5otekHrQ',
    appId: '1:617958281651:web:daaae15d2a7510ea79fbc6',
    messagingSenderId: '617958281651',
    projectId: 'isyeriegitimi-ece46',
    authDomain: 'isyeriegitimi-ece46.firebaseapp.com',
    databaseURL: 'https://isyeriegitimi-ece46-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'isyeriegitimi-ece46.appspot.com',
    measurementId: 'G-91C6X89LTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjnGiBM6ImBTmdiJq8tN8Dgf46zUJDIx8',
    appId: '1:617958281651:android:cb3bfec8ee3c54f279fbc6',
    messagingSenderId: '617958281651',
    projectId: 'isyeriegitimi-ece46',
    databaseURL: 'https://isyeriegitimi-ece46-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'isyeriegitimi-ece46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM1yaHcC1q4CtmjIfKPOUBa9FNj3V2_0w',
    appId: '1:617958281651:ios:4a243a397b73176879fbc6',
    messagingSenderId: '617958281651',
    projectId: 'isyeriegitimi-ece46',
    databaseURL: 'https://isyeriegitimi-ece46-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'isyeriegitimi-ece46.appspot.com',
    iosBundleId: 'com.example.etkinlikTakipProjesi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM1yaHcC1q4CtmjIfKPOUBa9FNj3V2_0w',
    appId: '1:617958281651:ios:9b8465c9b9e811e779fbc6',
    messagingSenderId: '617958281651',
    projectId: 'isyeriegitimi-ece46',
    databaseURL: 'https://isyeriegitimi-ece46-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'isyeriegitimi-ece46.appspot.com',
    iosBundleId: 'com.example.etkinlikTakipProjesi.RunnerTests',
  );
}
